### ISSUE TITLE
pyrlang v.0.7 build fails with Python 3.7.1

### ISSUE THREAD

**Issue by rlouf** [Pyrlang/Pyrlang#44]
First, thanks for your work in this! I am trying to orchestrate heavy computations with Python and this looks very promising.

Installing Python dependencies using `pip install -r requirements.txt` fails when trying to build gevent and greenlet because of compilation errors. This is likely due to the version of Cython used for gevent v1.2.1
 and greenlet v.0.4.12 is too old for Python 3.7.

Upgrading greenlet to 0.14.5 and gevent to 1.3.7 (latest releases) solves the issue. 

I can test other versions of python and submit a PR if that helps.

**Comment by rlouf** [comment]
There is another issue related with Python 3.7: since `async` is now a reserved keyword, and python raises a `SyntaxError` exception when reading the `pyrlang.async.XXX` imports. It can be easily fixed by renaming the submodule to something like `async_support`. Again, I can submit a PR if it helps.

**Comment by kvakvs** [comment]
If you are not using gevent, you can drop gevent/greenlets from the dependencies file.
If anything requires my attention i will not be able to look at it until the next week.

**Comment by rlouf** [comment]
I did end up dropping gevent/greenlet as you suggested. As for the issues with the `async` keyword I juste renamed the submodule. Now everything is working fine and I'm having a lot of fun!

**Comment by s2hc-johan** [comment]
Please let us know of your progress

**Comment by rlouf** [comment]
I got it to work, but I’m not sure where you want to go with this. I can submit a quick PR that renames the `async` folder and bumps `greenlet` and `gevent`’s versions.

**Comment by rlouf** [comment]
I can have a look at dropping adapter libraries as well but it would take a bit more time. Let me know!

**Comment by kvakvs** [comment]
You are welcome with the rename PR.
As to async PR that might take you a few days, so would be nice to set up a better comms channel to discuss it as you go, to avoid wasting day on something that doesn't work. Or just let me do it at my pace, next time i am putting more time into the project it may come in some weeks or months.

**Comment by kvakvs** [comment]
Merged, thanks!
