### ISSUE TITLE
py vs native discrepancies

### ISSUE THREAD

**Issue by s2hc-johan** [Pyrlang/Pyrlang#47]
The PR that fixed so that the codec module actually can import the rust implementation (https://github.com/Pyrlang/Term/pull/8), breaks pyrlang due to differences in how things are decoded. One bug I found and fixed but something makes the node be `str` when py implementation is used and `Atom` when rust implementation is used.

Row 336 in `pyrlang/node.py` will fail since the node is stored with key as str but the `receiver_node` is an `Atom`.  This got me thinking that maybe we should allow for Atom to be inherited from `str` as done in erlpack. I would guess that more often then not having equality between `Atom` and `str` would be the expected behaviour in most use cases. And since it's a type we can guarantee that a roundtrip back to Erlang land will convert it back to an `Atom`.

**Comment by kvakvs** [comment]
Atom for node should be a str if i recall my last idea correctly. Inheriting sounds about right, can you make it work or should this be an open issue for later?

**Comment by s2hc-johan** [comment]
I can fix, just wanted to discuss the idea first because there were some syntax that's gonna need to change so I didn't want to just do it.

**Comment by kvakvs** [comment]
Fixed a bug where Rust library decoded pid and ref having node as atom, while Python impl decoded them as strings. Now both create strings. https://github.com/Pyrlang/Term/commit/2c754df2fbc04fe43c080e3b64a52c46279ae0bc

**Comment by s2hc-johan** [comment]
think this is resolved, closing
