### ISSUE TITLE
Can't import pyrlang  Atom

### ISSUE THREAD

**Issue by marinakr** [Pyrlang/Pyrlang#48]
OTP 22
code main.py :
`from pyrlang import Node, Atom, GeventEngine # or AsyncioEngine`
run  `python main.py`
I get 
```Native term ETF codec library import failed, falling back to slower Python impl
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from pyrlang import Node, Atom, GeventEngine # or AsyncioEngine
ImportError: cannot import name 'Atom' from 'pyrlang' (/usr/local/lib/python3.7/site-packages/pyrlang/__init__.py)
```

**Comment by kvakvs** [comment]
`Atom` is now part of the Term library.
Please import from `term`.
The documentation might be slightly out of date here, did my best to update it when Term library was created.

**Comment by marinakr** [comment]
it works after `from term import Atom` and  add `git+git://github.com/Pyrlang/Term@master#egg=term`
