### ISSUE TITLE
Create on demand supervised python nodes from erlang/elixir

### ISSUE THREAD

**Issue by sezaru** [Pyrlang/Pyrlang#50]
Is it possible to start a python node on demand (from erlang/elixir code) and add it to a supervision tree?

I tried to find something about it in the docs without success.

Thanks

**Comment by kvakvs** [comment]
There is no supervision tree, only ability to monitor/link.
I think you should either organize your own python spawning from Erlang/Elixir (on local host), or create a small python node which will take spawn commands and start more Pythons (works on local or over the network).

**Comment by sezaru** [comment]
Thanks for the clarification and tips!

**Comment by s2hc-johan** [comment]
Although pyrlang is aimed at the glue making python behave as an erlang node, a python process still isn't as roubust as the erlang vm. 

We're preparing for an implementation of pyrlang where we will spawn nodes on demand. there will probably be a supervisor handling ports in wich we start pyrlang on the target port process. Then we'll use standard distributed erlang to communicate with it. So it will be that erlang applications can spawn, and if necessary kill the python nodes on demand.
