### ISSUE TITLE
Examples broken as a consequence of commit 7827635

### ISSUE THREAD

**Issue by acru-jdp** [Pyrlang/Pyrlang#56]
The signature of Process.__init__ no longer contains 'node_name', but the examples still try to pass it.

**Comment by acru-jdp** [comment]
Would you recommend that newbies to pyrlang work off that branch, rather than master?  If so, I think it could be helpful to signpost that, so that people coming it to the first time don't run into an immediate problem.

Thanks to the team for your hard work - it's looking really useful.

**Comment by s2hc-johan** [comment]
Well that's a valid point, I'm hacking around quite abit right now. Think it's at least as stable as main, but there are some changes, however think most of it is in `pyrlang2`. I think I'll update the examples in master.
